/*
 * Copyright 2010-2019 Australian Signals Directorate
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package au.gov.asd.acsc.constellation.preferences;

import java.io.File;
import javax.swing.JFileChooser;

public class ACSCOptionsPanel extends javax.swing.JPanel {

    private final ACSCOptionsPanelController controller;

    public ACSCOptionsPanel(final ACSCOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
    }

    public String getMaxmindUserId() {
        return maxmindUserId.getText();
    }

    public void setMaxmindUserId(final String userId) {
        maxmindUserId.setText(userId);
    }

    public String getVirusTotalAPIKey() {
        return virusTotalAPIKey.getText();
    }

    public void setVirusTotalAPIKey(final String apiKey) {
        virusTotalAPIKey.setText(apiKey);
    }

    public String getVirusTotalUrl() {
        return virusTotalUrl.getText();
    }

    public void setVirusTotalUrl(final String url) {
        virusTotalUrl.setText(url);
    }

    public String getMaxmindAPIKey() {
        return maxmindAPIKey.getText();
    }

    public void setMaxmindAPIKey(final String apiKey) {
        maxmindAPIKey.setText(apiKey);
    }

    public String getMaxmindCityDB() {
        return maxmindCityDB.getText();
    }

    public void setMaxmindCityDB(final String db) {
        maxmindCityDB.setText(db);
    }

    public String getMaxmindAnonDB() {
        return maxmindAnonDB.getText();
    }

    public void setMaxmindAnonDB(final String db) {
        maxmindAnonDB.setText(db);
    }

    public String getMaxmindISPDB() {
        return maxmindISPDB.getText();
    }

    public void setMaxmindISPDB(final String db) {
        maxmindISPDB.setText(db);
    }

    public String getMaxmindDomainDB() {
        return maxmindDomainDB.getText();
    }

    public void setMaxmindDomainDB(final String db) {
        maxmindDomainDB.setText(db);
    }

    public String getMaxmindConnectionTypeDB() {
        return maxmindConnectionTypeDB.getText();
    }

    public void setMaxmindConnectionTypeDB(final String db) {
        maxmindConnectionTypeDB.setText(db);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        maxmindUserIdLbl = new javax.swing.JLabel();
        maxmindUserId = new javax.swing.JTextField();
        maxmindAPIKeyLbl = new javax.swing.JLabel();
        maxmindAPIKey = new javax.swing.JTextField();
        maxmindCityDBLbl = new javax.swing.JLabel();
        maxmindCityDB = new javax.swing.JTextField();
        maxmindCityDBButton = new javax.swing.JButton();
        maxmindAnonDBLbl = new javax.swing.JLabel();
        maxmindAnonDB = new javax.swing.JTextField();
        maxmindAnonDBButton = new javax.swing.JButton();
        maxmindISPDBLbl = new javax.swing.JLabel();
        maxmindISPDB = new javax.swing.JTextField();
        maxmindISPDBButton = new javax.swing.JButton();
        maxmindDomainDBLbl = new javax.swing.JLabel();
        maxmindDomainDB = new javax.swing.JTextField();
        maxmindDomainDBButton = new javax.swing.JButton();
        maxmindConnectionTypesDBLbl = new javax.swing.JLabel();
        maxmindConnectionTypeDB = new javax.swing.JTextField();
        maxmindConnectionTypeDBButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        virusTotalUrlLbl = new javax.swing.JLabel();
        virusTotalUrl = new javax.swing.JTextField();
        virusTotalAPIKeyLbl = new javax.swing.JLabel();
        virusTotalAPIKey = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(maxmindUserIdLbl, org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindUserIdLbl.text")); // NOI18N

        maxmindUserId.setText(org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindUserId.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(maxmindAPIKeyLbl, org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindAPIKeyLbl.text")); // NOI18N

        maxmindAPIKey.setText(org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindAPIKey.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(maxmindCityDBLbl, org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindCityDBLbl.text")); // NOI18N

        maxmindCityDB.setText(org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindCityDB.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(maxmindCityDBButton, org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindCityDBButton.text")); // NOI18N
        maxmindCityDBButton.setMargin(new java.awt.Insets(2, 0, 2, 0));
        maxmindCityDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxmindCityDBButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(maxmindAnonDBLbl, org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindAnonDBLbl.text")); // NOI18N

        maxmindAnonDB.setText(org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindAnonDB.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(maxmindAnonDBButton, org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindAnonDBButton.text")); // NOI18N
        maxmindAnonDBButton.setMargin(new java.awt.Insets(2, 0, 2, 0));
        maxmindAnonDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxmindAnonDBButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(maxmindISPDBLbl, org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindISPDBLbl.text")); // NOI18N

        maxmindISPDB.setText(org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindISPDB.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(maxmindISPDBButton, org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindISPDBButton.text")); // NOI18N
        maxmindISPDBButton.setMargin(new java.awt.Insets(2, 0, 2, 0));
        maxmindISPDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxmindISPDBButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(maxmindDomainDBLbl, org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindDomainDBLbl.text")); // NOI18N

        maxmindDomainDB.setText(org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindDomainDB.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(maxmindDomainDBButton, org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindDomainDBButton.text")); // NOI18N
        maxmindDomainDBButton.setMargin(new java.awt.Insets(2, 0, 2, 0));
        maxmindDomainDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxmindDomainDBButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(maxmindConnectionTypesDBLbl, org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindConnectionTypesDBLbl.text")); // NOI18N

        maxmindConnectionTypeDB.setText(org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindConnectionTypeDB.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(maxmindConnectionTypeDBButton, org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.maxmindConnectionTypeDBButton.text")); // NOI18N
        maxmindConnectionTypeDBButton.setMargin(new java.awt.Insets(2, 0, 2, 0));
        maxmindConnectionTypeDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxmindConnectionTypeDBButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxmindUserIdLbl)
                            .addComponent(maxmindAPIKeyLbl)
                            .addComponent(maxmindCityDBLbl))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(maxmindCityDBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(maxmindUserId)
                                    .addComponent(maxmindAPIKey, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxmindAnonDBLbl)
                            .addComponent(maxmindISPDBLbl)
                            .addComponent(maxmindDomainDBLbl)
                            .addComponent(maxmindConnectionTypesDBLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(maxmindConnectionTypeDB, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                    .addComponent(maxmindDomainDB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maxmindDomainDBButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(maxmindConnectionTypeDBButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(maxmindAnonDB)
                                    .addComponent(maxmindISPDB)
                                    .addComponent(maxmindCityDB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(maxmindISPDBButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(maxmindAnonDBButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxmindUserIdLbl)
                    .addComponent(maxmindUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxmindAPIKeyLbl)
                    .addComponent(maxmindAPIKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxmindCityDBLbl)
                    .addComponent(maxmindCityDBButton)
                    .addComponent(maxmindCityDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxmindAnonDBLbl)
                    .addComponent(maxmindAnonDBButton)
                    .addComponent(maxmindAnonDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxmindISPDBLbl)
                    .addComponent(maxmindISPDBButton)
                    .addComponent(maxmindISPDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxmindDomainDBLbl)
                    .addComponent(maxmindDomainDBButton)
                    .addComponent(maxmindDomainDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxmindConnectionTypesDBLbl)
                    .addComponent(maxmindConnectionTypeDBButton)
                    .addComponent(maxmindConnectionTypeDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(virusTotalUrlLbl, org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.virusTotalUrlLbl.text")); // NOI18N

        virusTotalUrl.setText(org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.virusTotalUrl.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(virusTotalAPIKeyLbl, org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.virusTotalAPIKeyLbl.text")); // NOI18N

        virusTotalAPIKey.setText(org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.virusTotalAPIKey.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(virusTotalUrlLbl)
                    .addComponent(virusTotalAPIKeyLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(virusTotalAPIKey)
                    .addComponent(virusTotalUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(virusTotalUrlLbl)
                    .addComponent(virusTotalUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(virusTotalAPIKeyLbl)
                    .addComponent(virusTotalAPIKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(295, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(ACSCOptionsPanel.class, "ACSCOptionsPanel.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void maxmindConnectionTypeDBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxmindConnectionTypeDBButtonActionPerformed
        final JFileChooser fc = new JFileChooser(System.getProperty("user.home"));
        final String dir = maxmindConnectionTypeDB.getText().trim();
        if (!dir.isEmpty()) {
            fc.setSelectedFile(new File(dir));
        }
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if (fc.showDialog(this, "Select Maxmind Connection Type DB Location") == JFileChooser.APPROVE_OPTION) {
            final String fnam = fc.getSelectedFile().getPath();
            maxmindConnectionTypeDB.setText(fnam);
        }
    }//GEN-LAST:event_maxmindConnectionTypeDBButtonActionPerformed

    private void maxmindDomainDBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxmindDomainDBButtonActionPerformed
        final JFileChooser fc = new JFileChooser(System.getProperty("user.home"));
        final String dir = maxmindDomainDB.getText().trim();
        if (!dir.isEmpty()) {
            fc.setSelectedFile(new File(dir));
        }
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if (fc.showDialog(this, "Select Maxmind Domain DB Location") == JFileChooser.APPROVE_OPTION) {
            final String fnam = fc.getSelectedFile().getPath();
            maxmindDomainDB.setText(fnam);
        }
    }//GEN-LAST:event_maxmindDomainDBButtonActionPerformed

    private void maxmindISPDBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxmindISPDBButtonActionPerformed
        final JFileChooser fc = new JFileChooser(System.getProperty("user.home"));
        final String dir = maxmindISPDB.getText().trim();
        if (!dir.isEmpty()) {
            fc.setSelectedFile(new File(dir));
        }
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if (fc.showDialog(this, "Select Maxmind ISP DB Location") == JFileChooser.APPROVE_OPTION) {
            final String fnam = fc.getSelectedFile().getPath();
            maxmindISPDB.setText(fnam);
        }
    }//GEN-LAST:event_maxmindISPDBButtonActionPerformed

    private void maxmindAnonDBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxmindAnonDBButtonActionPerformed
        final JFileChooser fc = new JFileChooser(System.getProperty("user.home"));
        final String dir = maxmindAnonDB.getText().trim();
        if (!dir.isEmpty()) {
            fc.setSelectedFile(new File(dir));
        }
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if (fc.showDialog(this, "Select Maxmind Anonymous DB Location") == JFileChooser.APPROVE_OPTION) {
            final String fnam = fc.getSelectedFile().getPath();
            maxmindAnonDB.setText(fnam);
        }
    }//GEN-LAST:event_maxmindAnonDBButtonActionPerformed

    private void maxmindCityDBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxmindCityDBButtonActionPerformed
        final JFileChooser fc = new JFileChooser(System.getProperty("user.home"));
        final String dir = maxmindCityDB.getText().trim();
        if (!dir.isEmpty()) {
            fc.setSelectedFile(new File(dir));
        }
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if (fc.showDialog(this, "Select Maxmind City DB Location") == JFileChooser.APPROVE_OPTION) {
            final String fnam = fc.getSelectedFile().getPath();
            maxmindCityDB.setText(fnam);
        }
    }//GEN-LAST:event_maxmindCityDBButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField maxmindAPIKey;
    private javax.swing.JLabel maxmindAPIKeyLbl;
    private javax.swing.JTextField maxmindAnonDB;
    private javax.swing.JButton maxmindAnonDBButton;
    private javax.swing.JLabel maxmindAnonDBLbl;
    private javax.swing.JTextField maxmindCityDB;
    private javax.swing.JButton maxmindCityDBButton;
    private javax.swing.JLabel maxmindCityDBLbl;
    private javax.swing.JTextField maxmindConnectionTypeDB;
    private javax.swing.JButton maxmindConnectionTypeDBButton;
    private javax.swing.JLabel maxmindConnectionTypesDBLbl;
    private javax.swing.JTextField maxmindDomainDB;
    private javax.swing.JButton maxmindDomainDBButton;
    private javax.swing.JLabel maxmindDomainDBLbl;
    private javax.swing.JTextField maxmindISPDB;
    private javax.swing.JButton maxmindISPDBButton;
    private javax.swing.JLabel maxmindISPDBLbl;
    private javax.swing.JTextField maxmindUserId;
    private javax.swing.JLabel maxmindUserIdLbl;
    private javax.swing.JTextField virusTotalAPIKey;
    private javax.swing.JLabel virusTotalAPIKeyLbl;
    private javax.swing.JTextField virusTotalUrl;
    private javax.swing.JLabel virusTotalUrlLbl;
    // End of variables declaration//GEN-END:variables
}
